// TanStack Query keys. One place, so invalidation after a mutation can target a whole domain.
import type {
  AdminUserQuery,
  AnomalyListQuery,
  AuditQuery,
  EventListQuery,
  ExplanationQuery,
  FloatType,
  ForecastQuery,
  GroupBy,
  ImpactComparisonQuery,
  Lang,
  ImpactQuery,
  LlmLogQuery,
  NotificationListQuery,
  HelpRequestListQuery,
  RequestListQuery,
  RiskListQuery,
  SwapListQuery,
} from "./types";

export const qk = {
  agent: {
    all: ["agent"] as const,
    summary: (id: number) => ["agent", id, "summary"] as const,
    forecast: (id: number, q: ForecastQuery = {}) => ["agent", id, "forecast", q] as const,
    stockout: (id: number) => ["agent", id, "stockout"] as const,
    risk: (id: number) => ["agent", id, "risk"] as const,
    explanations: (id: number, q: ExplanationQuery = {}) => ["agent", id, "explanations", q] as const,
    recommendation: (id: number) => ["agent", id, "recommendation"] as const,
    runway: (id: number, float: FloatType) => ["agent", id, "runway", float] as const,
    narration: (id: number, float: FloatType, lang: Lang) => ["agent", id, "narration", float, lang] as const,
    whatIf: (id: number, float: FloatType, delta: number) => ["agent", id, "whatif", float, delta] as const,
  },
  events: (q: EventListQuery = {}) => ["events", q] as const,
  eventsAll: ["events"] as const,
  admin: {
    all: ["admin"] as const,
    overview: ["admin", "overview"] as const,
    users: { all: ["admin", "users"] as const, list: (q: AdminUserQuery = {}) => ["admin", "users", q] as const },
    org: ["admin", "org"] as const,
    audit: (q: AuditQuery = {}) => ["admin", "audit", q] as const,
    data: ["admin", "data"] as const,
    assumptions: ["admin", "data", "assumptions"] as const,
    models: ["admin", "models"] as const,
    drift: ["admin", "drift"] as const,
    jobs: ["admin", "jobs"] as const,
    llmLogs: (q: LlmLogQuery = {}) => ["admin", "llm", "logs", q] as const,
    llmUsage: (days: number) => ["admin", "llm", "usage", days] as const,
  },
  copilotSuggestions: (lang: Lang) => ["copilot", "suggestions", lang] as const,
  riskList: (q: RiskListQuery = {}) => ["risk-list", q] as const,
  map: { all: ["map"] as const, agents: (atHour: number) => ["map", "agents", atHour] as const },
  requests: { all: ["requests"] as const, list: (q: RequestListQuery = {}) => ["requests", q] as const },
  swaps: { all: ["swaps"] as const, list: (q: SwapListQuery = {}) => ["swaps", q] as const },
  anomalies: {
    all: ["anomalies"] as const,
    list: (q: AnomalyListQuery = {}) => ["anomalies", "list", q] as const,
    detail: (id: number) => ["anomalies", id] as const,
  },
  notifications: {
    all: ["notifications"] as const,
    list: (q: NotificationListQuery = {}) => ["notifications", q] as const,
  },
  help: {
    all: ["help-requests"] as const,
    mine: (q: HelpRequestListQuery = {}) => ["help-requests", "mine", q] as const,
    inbox: (q: HelpRequestListQuery = {}) => ["help-requests", "inbox", q] as const,
    item: (id: number) => ["help-requests", "item", id] as const,
    admin: (q: HelpRequestListQuery = {}) => ["help-requests", "admin", q] as const,
    settings: ["help-requests", "admin", "settings"] as const,
    trigger: ["help-requests", "admin", "trigger"] as const,
    demo: ["help-requests", "admin", "demo"] as const,
    agents: ["help-requests", "agents"] as const,
  },
  system: { freshness: ["system", "freshness"] as const, llm: ["llm", "status"] as const },
  modelCard: (lang: string) => ["responsible-ai", "model-card", lang] as const,
  search: (q: string) => ["search", q] as const,
  profile: ["users", "me", "profile"] as const,
  impact: (q: ImpactQuery = {}) => ["impact", "summary", q] as const,
  impactComparison: (q: ImpactComparisonQuery = {}) => ["impact", "comparison", q] as const,
  fairness: (groupBy: GroupBy) => ["responsible-ai", "fairness", groupBy] as const,
  briefing: (lang: Lang) => ["llm", "distributor-briefing", lang] as const,
  anomalyNarrative: (id: number, lang: Lang) => ["llm", "anomaly-narrative", id, lang] as const,
};
